; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; [env:upesy_wroom]
; platform = espressif32
; board = upesy_wroom
; debug_tool = cmsis-dap
; framework = arduino
; monitor_speed = 115200
; board_build.partitions = huge_app.csv
; lib_deps = 
; 	bblanchon/ArduinoJson@^6.21.3
; 	esphome/ESP32-audioI2S@^2.0.7
; 	; links2004/WebSockets@^2.4.1
; 	gilmaimon/ArduinoWebsockets@^0.5.3


; [env:esp32_wrover]
; platform = espressif32
; board = upesy_wrover      ; 【修改1】将开发板型号改为 wrover
; debug_tool = cmsis-dap
; framework = arduino
; monitor_speed = 115200

; ; 【修改2】修改分区表，释放出 3MB 的超大 Flash 空间给主程序
; board_build.partitions = huge_app.csv 

; ; 【修改3】极其重要：开启 PSRAM 支持！否则 WROVER 的外挂内存等同于摆设
; build_flags = 
;     -DBOARD_HAS_PSRAM
;     -mfix-esp32-psram-cache-issue

; lib_deps = 
;     bblanchon/ArduinoJson@^6.21.3
;     esphome/ESP32-audioI2S@^2.0.7
;     ; links2004/WebSockets@^2.4.1
;     gilmaimon/ArduinoWebsockets@^0.5.3


[env:esp32s3]
platform = espressif32
board = 4d_systems_esp32s3_gen4_r8n16
; board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

upload_speed = 921600

; 1. 指定文件系统为 LittleFS (默认是 SPIFFS)
board_build.filesystem = littlefs

; 依然释放 10MB 超大 Flash 空间给主程序
board_build.partitions = Myhuge_app.csv 


board_build.arduino.memory_type = qio_opi
build_flags = 
    -DBOARD_HAS_PSRAM         ; 开启 S3 的超高速外挂内存
    -DARDUINO_USB_CDC_ON_BOOT=0 ; 【S3专属保命符】开启原生 USB 串口打印，否则你看不到系统心跳和报错！

lib_deps = 
    zinggjm/GxEPD2@^1.5.0
    esphome/ESP32-audioI2S@^2.0.7
    gilmaimon/ArduinoWebsockets@^0.5.3
    adafruit/Adafruit GFX Library @ ^1.11.9
    bblanchon/ArduinoJson@^7.0.0
    https://github.com/tignioj/ArduinoZlib
    acrandal/RevEng PAJ7620